# Generated by Django 5.0.4 on 2024-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_date',
            field=models.DateTimeField(verbose_name='дата первой отправки'),
        ),
    ]
