# Generated by Django 5.0.4 on 2024-06-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailing_first_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='создана', null=True, verbose_name='статус'),
        ),
    ]
