# Generated by Django 5.0.4 on 2024-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_alter_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='check_periodicity',
            field=models.IntegerField(default='0', verbose_name='дней до следующей отправки'),
        ),
    ]
