# Generated by Django 5.0.4 on 2024-06-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_mailing_owner_recipientclient_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_edit_status', 'Can edit status'), ('can_edit_periodicity', 'Can edit periodicity'), ('can_edit_clients', 'Can edit clients')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='recipientclient',
            options={'permissions': [('can_edit_email', 'Can edit email'), ('can_edit_full_name', 'Can edit full_name'), ('can_edit_comment', 'Can edit comment')], 'verbose_name': 'Клиент получатель', 'verbose_name_plural': 'Клиенты получатели'},
        ),
    ]
